version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches: 
              only:
                - main
          requires:
            - build 


# Define the jobs we want to run for this project
jobs:
  build:
    working_directory: ~/GroupThirteen
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
          name: update-npm
          command: 'sudo npm install -g npm@8.1.4'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install       
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  deploy:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/NotesAppGroup13
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f2:d9:99:3a:54:31:00:5b:4d:57:10:c7:4c:82:66:4b"
      - run:
          name: Install NVM
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install Node.js and npm
          command: |
            nvm install 14
            nvm use 14
            nvm alias default 14
            node -v
            npm -v
      - run:
          name: Deploy to EC2
          command: |
            chmod +x update.sh
            scp update.sh $SSH_USER@$SSH_HOST:/home/$SSH_USER/update.sh
            scp -r .circleci/ $SSH_USER@$SSH_HOST:/home/$SSH_USER/.circleci/
            ssh -tt $SSH_USER@$SSH_HOST 'sudo bash update.sh'
